ZRAM0=true
ZRAM0_SIZE="25%"
ZRAM0_MEM_LIMIT="4G"
ZRAM0_COMP_ALGO="lz4"
ZRAM0_ALGO_PARAMS="level=8 dict=/etc/dict"
ZRAM0_PRIORITY="32767"
ZRAM0_DISCARD_OPT="both"

ZRAM1=true
ZRAM1_BACKING_DEV=/dev/sda2
ZRAM1_BACKING_DEV=